<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once(dirname(__DIR__) . '/Packages/Libraries/autoload.php');
require_once(dirname(__DIR__) . '/Configuration/application.php');


$context = WPFLOW_CONTEXT ?: 'Development';
$configuration = \wpFlow\Core\ApplicationConfiguration\ApplicationConfiguration::boot($context);
$configuration->defineConstants();

/**
 * Defining the tableprefix for Wordpress
 * @var  $table_prefix
 */
$table_prefix = 'wpFlow_';


require_once(ABSPATH . 'wp-settings.php');
